version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: vendas
    ports:
      - "3308:3306"
  postgres:
    image: postgres:16
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: vendas